[package]
name = "gif_to_ascii_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
gif = "0.12.0"
image = "0.24.6"
term_size = "0.3.2"
